spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "3.0"

cards:
  message: "Welcome to Cards service prod environment"
  contactDetails:
    name: "John Doe cards PROD"
    email: "Ig7dF@examplePROD.com"
  onCallSupport:
    - 54322
    - 87654